### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-herd#293] opened 2017-09-05 18:18 UTC
on this page:
https://herd.ceylon-lang.org/modules/ceylon.json/1.3.3/members
the text "shared ceylon.json::parse" links to this dead page:
https://herd.ceylon-lang.org/repo/1/ceylon/json/1.3.3/module-doc/api/index.html%23parse

**Comment by FroMage** [comment] 2017-09-06 19:20
Dupe of #291

**Closed by FroMage** 2017-09-06 19:20 UTC
